### ISSUE TITLE
error when using maps coming from flexibility analyses protocols

### ISSUE THREAD

**Issue by CPM46** [3dem/model-angelo#108]
Hi everyone,
I'm having the attached error log when trying to run modelangelo with a map coming from running flexibility analyses tools. It was able to run it OK when using a map coming from standard 3D refinement, but not for the other one.

Have you ever seen this issue before? and if so, do you know how to solve this?

Thanks a lot in advance!

[run_stderr.log](https://github.com/3dem/model-angelo/files/15472319/run_stderr.log)

**Comment by jamaliki** [comment]
Hi, where you able to resolve this?

**Comment by CPM46** [comment]
Hi Kiarash,
thanks for the reply, indeed there was no error with modelangelo at all, but we didn't notice that the real pixel size on the map was not the right one and was not matching the pixel size of the mask. Double checking these in chimera allowed us to find the issue and once corrected, everything ran ok.

Thanks for the help!
