### ISSUE TITLE
question about using the model-angelo with no sequence

### ISSUE THREAD

**Issue by PeterVanF** [3dem/model-angelo#110]
Hi,
I have recently been using Model-Angelo to identify an unknown density determined by cryo-EM with a local resolution of about 4 Å. I'm uncertain whether this region belongs to RNA or protein. Despite the results being incomplete and fragmented, I used Model-Angelo (no-sequence) to build its atomic model. Some regions were identified by Model-Angelo as nucleoside bases, while others were identified as amino acids. 

I would like to know if these results are reliable. Are there confidence or probability values available that can help me analyze this structure more accurately?

**Comment by jamaliki** [comment]
Hi,

If you run the program with the flag "--keep-intermediate-results" then it should save extra files into directories named "gnn_output_round_*". If you look at the last folder, "gnn_output_round_3", there should be a file called output_aa_probabilities.aap which gives you the probability of every residue (in order) for every class. You can then see what the relative probabilities between protein and nucleotide are. 

Best,
Kiarash.

**Comment by PeterVanF** [comment]
I got it. Thank you!
