### ISSUE TITLE
KeyError when downloading original_no_seq weights

### ISSUE THREAD

**Issue by cjroberts** [3dem/model-angelo#12]
Hi Model-Angelo Team,

I am following your instructions for setting up a shared install on our cluster. (I am trying in my own space first before doing a central install.)

Model-Angelo seems to install correctly and download the original bundle of weights successfully, but when it comes to downloading the original_no_seq bundle I get the following error:

```
Setting up bundle with name: original_no_seq for the first time.
Traceback (most recent call last):
  File "/gpfs2/well/rescomp/users/iub031/src/model-angelo/model_angelo/utils/setup_weights.py", line 17, in <module>
    model_dst = download_and_install_model(args.bundle_name)
  File "/well/rescomp/users/iub031/conda/skylake/envs/model_angelo/lib/python3.9/site-packages/model_angelo-0.0.1-py3.9.egg/model_angelo/utils/torch_utils.py", line 456, in download_and_install_model
    bundle_name_to_link[bundle_name],
KeyError: 'original_no_seq'
```

This occurs when sourcing the install script with the --download-weights option.

Please could you help?

**Comment by KiSchnelle** [comment]
Try replacing in the install scropt original_no_seq with original_no_sequence. Seems to be the correct key in the download_and_install_model function inside the torch_utils.py

**Comment by cjroberts** [comment]
Thanks, @KiSchnelle. If I do this I get the following error after the download of the first file for original_nosequence:
```
Traceback (most recent call last):
  File "/gpfs2/well/rescomp/users/iub031/src/model-angelo/model_angelo/utils/setup_weights.py", line 17, in <module>
    model_dst = download_and_install_model(args.bundle_name)
  File "/well/rescomp/users/iub031/conda/skylake/envs/model_angelo/lib/python3.9/site-packages/model_angelo-0.0.1-py3.9.egg/model_angelo/utils/torch_utils.py", line 465, in download_and_install_model
    with open(os.path.join(dest, "success.txt"), "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/well/rescomp/users/iub031/model_angelo_weights/hub/checkpoints/model_angelo/original_no_sequence/success.txt'
``` 
Model-Angelo has created the directory `/well/rescomp/users/iub031/model_angelo_weights/hub/checkpoints/model_angelo/original_no_seq`.

There is also a reference to original_no_seq in `model_angelo/apps/build_no_seq.py`:
```
    advanced_args.add_argument(
        "--model-bundle-name",
        type=str,
        default="original_no_seq",
        help="Inference model bundle name",
    )
```
I will try changing the key in the dictionary inside `torch_utils.py` and check if that works.

**Comment by jamaliki** [comment]
Hi @cjroberts ,

Sorry, this is a bug I introduced on Friday. If you pull the new code, I have now  fixed it. The fix commit is here: 11adfad5ce4890ba53ad3274461a8bfb164e1bf9

Thank you for using ModelAngelo!

Best,
Kiarash.

**Comment by KiSchnelle** [comment]
Thanks!:)

If you run it step by step not with the install script and changed the key in the torch_utlis.py you got to do again the
```
setup.py install
```
so the model_angelo-0.0.1-py3.9.egg is build again with the changed code.

cheers
Kilian

**Comment by cjroberts** [comment]
Thank you for the quick fix, @jamaliki!
