### ISSUE TITLE
What would be the recomended way to update model angelo

### ISSUE THREAD

**Issue by pconesa** [3dem/model-angelo#14]
I'm asking in case there is a "shorted method" than removing the installation and starting again

I guess models could be in a different folder?

model_angelo setup.py installed in editable mode + git pull?

**Comment by jamaliki** [comment]
Do you mean if the weights are updated? The only real thing that would be updated is the model_angelo code itself, which if you `git pull` again and run `python setup.py install` will update. Does that answer your question?

**Comment by pconesa** [comment]
I think so, most time part of the installation are:

creating the environment
and "downloading/preparing" models (apart from downloading and extracting models, does anything else happen)?

**Comment by jamaliki** [comment]
No, nothing apart from downloading and extracting the models.

**Comment by pconesa** [comment]
Nice, this was useful. If you are willing to contribute to the scipion plugin and make it better with your expertise, you are more than welcome. Let me know.

**Comment by jamaliki** [comment]
Sure! If you could point me to where the development is taking place.

**Comment by pconesa** [comment]
I just uploaded a working version of the plugin.... here: https://github.com/scipion-em/scipion-em-modelangelo

Protocol looks like this:

![image](https://user-images.githubusercontent.com/785633/195106695-aa437c3e-a631-4422-a438-508be1ade2de.png)

The installation part is done here, you might be able to understand how we are doing it:
https://github.com/scipion-em/scipion-em-modelangelo/blob/devel/modelangelo/__init__.py#L73

Execution part is here: https://github.com/scipion-em/scipion-em-modelangelo/blob/devel/modelangelo/protocols/protocol_model_angelo.py#L90

NOTE: Output is taking the wrong files. I'll fix this.

**Comment by jamaliki** [comment]
Looks great :+1:
