### ISSUE TITLE
Return error exit code

### ISSUE THREAD

**Issue by pconesa** [3dem/model-angelo#16]
Hi, it's me again. When modelangelo fails it actually does nor return any exit code and therefore programs calling modelangelo fail to detect the error.

Would it be possible to implement this? 

Thanks.

**Comment by pconesa** [comment]
Great! I'll test it and get back here.

**Comment by pconesa** [comment]
Working fine! Thanks!

**Comment by pconesa** [comment]
Have we lost the exit code in the latest code?

**Comment by pconesa** [comment]
After a git pull (I'm using "main" branch) I'm bask to where I when posting this issue. 

I remember vaguely you added a sys.exit() call somewhere here but is not there anymore.

https://github.com/3dem/model-angelo/blob/main/model_angelo/apps/build.py#L119

**Comment by pconesa** [comment]
Wait! maybe I'm wrong and my installation is pointing to a old version.. let me check

**Comment by jamaliki** [comment]
I didn't remove the sys exit, so it should still be the same

**Comment by pconesa** [comment]
Sorry, my installation had an old version without it. After updating it to current main code all works.
