### ISSUE TITLE
GNN model ref failed

### ISSUE THREAD

**Issue by TRAP-man** [3dem/model-angelo#17]
hey,
I wanted to try to build a model in my recent map, but GNN module failed to run. Ca tracing worked within 6 minutes or so, but GNN stopped when starting round 1. 
Could anybody tell me how to fix this. Below you can find a log file of a job that was started and failed.
[model_angelo.log](https://github.com/3dem/model-angelo/files/9753083/model_angelo.log)

Thanks in advance

**Comment by jamaliki** [comment]
Hi,

This is interesting. Would you be willing to share the see_alpha_output_ca.cif file? If the data is confidential, you can send it to my email at [kjamali](mailto:kjamali@mrc-lmb.cam.ac.uk).

Best,
Kiarash.

**Comment by jamaliki** [comment]
Oh I see. So the C alpha part did not work. Could you share your map? Something is wrong here.

**Comment by TRAP-man** [comment]
I have send it to your mailbox
