### ISSUE TITLE
the model is shown as lines; IndexError: arrays used as indices must be of integer (or boolean) type

### ISSUE THREAD

**Issue by DmitrySemchonok** [3dem/model-angelo#21]
Hello Kiarash, @jamaliki 

After running model-angelo with a fasta file, the final result (see_alpha_output_ca.cif) is shown as direct lines and looks more like a hedgehog. 

<img width="987" alt="Screenshot 2022-11-01 at 12 19 55" src="https://user-images.githubusercontent.com/21281315/199221828-6d920883-c328-4ce3-a13c-3d5d0a53e017.png">

The results in the other folders (output_ca_points_before_pruning.cif) look like that 

<img width="1115" alt="Screenshot 2022-11-01 at 12 20 39" src="https://user-images.githubusercontent.com/21281315/199221962-c4d8645e-33b4-44bc-b451-85d60c43f5d9.png">

As for the gnn_output_round_ folders - the results are looking somewhat better 
<img width="1152" alt="Screenshot 2022-11-01 at 12 22 34" src="https://user-images.githubusercontent.com/21281315/199222237-59e6eb76-e8ff-4dde-9b78-70a5d6a07faa.png">

But if I want to see only the alpha-helices and hide atoms, I see this
<img width="1140" alt="Screenshot 2022-11-01 at 12 23 26" src="https://user-images.githubusercontent.com/21281315/199222344-a1196b24-db47-41ac-ba8f-7b2b089a34c8.png">

How could you interpret the results?
Did something go wrong?

Please see the model-angelo log below. It seems that it has an error. 
Is there a way to fix it and the model itself?
[model_angelo.log](https://github.com/3dem/model-angelo/files/9909346/model_angelo.log)

Kind regards,
Dmitry

**Comment by jamaliki** [comment]
Hi @DmitrySemchonok ,

This is very strange. What is the resolution of the map? Would you be willing to send the sequence and the map to me so I can debug this?

Best,
Kiarash.

**Comment by lyw8120** [comment]
> Hi @DmitrySemchonok ,
> 
> This is very strange. What is the resolution of the map? Would you be willing to send the sequence and the map to me so I can debug this?
> 
> Best, Kiarash.

was this bug solved? 

best wishes
