### ISSUE TITLE
install issue for windows

### ISSUE THREAD

**Issue by lockye6** [3dem/model-angelo#25]
<img width="863" alt="install issue" src="https://user-images.githubusercontent.com/118562766/202778160-7ce55669-948b-4bd3-be6a-3c300c7632c8.png">

I followed the install instruction and when I run the install_script.sh it did show already installed. However, when I tried the last step with 
"model_angelo build -h", it is not working.  Appreciate any help.

**Comment by jamaliki** [comment]
Hi,
ModelAngelo has currently not been tested on Windows. However, it should work on the Windows Subsystem for Linux. Please see [here](https://learn.microsoft.com/en-us/windows/wsl/install).

**Comment by lockye6** [comment]
> Hi, ModelAngelo has currently not been tested on Windows. However, it should work on the Windows Subsystem for Linux. Please see [here](https://learn.microsoft.com/en-us/windows/wsl/install).
Thank you so much !
