### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by DmitrySemchonok** [3dem/model-angelo#3]
Dear colleagues,

I have installation issue on both centos and mac systems.

After installation, on the step 3 (conda activate model_angelo). 

When I run model_angelo build -h   -- nothing happens 

_-on centos_
[user@dataanalysisserver1 model_angelo]$ conda activate model_angelo
(model_angelo) model_angelo build -h
bash: model_angelo: command not found...

_- on mac_
    import torch
ModuleNotFoundError: No module named 'torch'

Any ideas?

Thank you.

Sincerely,
Dmitry
![centos](https://user-images.githubusercontent.com/21281315/193882237-0e09944a-5668-45fe-bb26-293135970dab.png)
![mac](https://user-images.githubusercontent.com/21281315/193882255-1506b559-4064-4487-a8ba-46cd1bc72ae0.png)

**Comment by jamaliki** [comment]
Hi @DmitrySemchonok , did you get any errors while running the installation script on centos?

Also, the problem for MacOS is that the CUDA toolkit is not available for Mac. If you want to still give this a go, you'd have to run  `conda install pytorch torchvision torchaudio -c pytorch` in the model_angelo environment, but then you can't use GPUs, so everything will be very slow. Not recommended.

**Comment by DmitrySemchonok** [comment]
> conda install pytorch torchvision torchaudio -c pytorch

Hello Kiarash @jamaliki, 

I tried to install it again and then got the following error:
============================================
[user@dataanalysisserver1 ~]$ cd Documents/
[user@dataanalysisserver1 Documents]$ cd model-angelo-main/
[user@dataanalysisserver1 model-angelo-main]$ cd model_angelo/
[user@dataanalysisserver1 model_angelo]$ bash install_script.sh
bash: install_script.sh: No such file or directory
[user@dataanalysisserver1 model_angelo]$ cd ..
[user@dataanalysisserver1 model-angelo-main]$ bash install_script.sh
which: no activate in (/home/user/Data/Software/cryosparc/cryosparc_master/bin:/usr/local/cuda-11.3/bin:/home/user/Data/Software/phenix-1.20.1-4487/build/bin:/home/user/Data/Software/ccp4-8.0/etc:/home/user/Data/Software/ccp4-8.0/bin:/home/user/Data/Software/cryosparc/cryosparc_master/bin:/usr/local/cuda-11.3/bin:/home/user/Data/Software/miniconda/condabin:/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/home/user/Data/Software/Relion/bin:/usr/lib64/openmpi/bin:/home/user/.local/bin:/home/user/bin:/home/user/Data/Software/Relion/bin:/usr/lib64/openmpi/bin)
install_script.sh: line 31: source: model_angelo: is a directory
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Retrieving notices: ...working... done
install_script.sh: line 37: pip: command not found
  File "setup.py", line 12
    sys.path.insert(0, f"{os.path.dirname(__file__)}/model_angelo")
                                                                 ^
SyntaxError: invalid syntax
Did not download weights because the flag -w or --download-weights was not specified
[user@dataanalysisserver1 model-angelo-main]$ 

==========================================

By the way, the step 3, if I am not mistaking, should be "cd model-angelo-main" unstead of "cd model-angelo"
For me the 
cd model-angelo
bash install_script.sh

did not work.

Kind regards,
Dmitry

**Comment by jamaliki** [comment]
I think there might be an issue in how you installed `conda` How did you do it? This in your path `/home/user/Data/Software/miniconda/condabin` looks incorrect to me. It should be `/home/user/Data/Software/miniconda/conda/bin`.

**Comment by jamaliki** [comment]
Could you pull the newest commit and try now @DmitrySemchonok

**Comment by DmitrySemchonok** [comment]
[user@dataanalysisserver1 model-angelo-main]$ bash install_script.sh
which: no activate in (/home/user/Data/Software/cryosparc/cryosparc_master/bin:/usr/local/cuda-11.3/bin:/home/user/Data/Software/phenix-1.20.1-4487/build/bin:/home/user/Data/Software/ccp4-8.0/etc:/home/user/Data/Software/ccp4-8.0/bin:/home/user/Data/Software/cryosparc/cryosparc_master/bin:/usr/local/cuda-11.3/bin:/home/user/Data/Software/miniconda/condabin:/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/home/user/Data/Software/Relion/bin:/usr/lib64/openmpi/bin:/home/user/.local/bin:/home/user/bin:/home/user/Data/Software/Relion/bin:/usr/lib64/openmpi/bin)
install_script.sh: line 31: source: model_angelo: is a directory
Collecting package metadata (current_repodata.json): done



Hello Kiarash @jamaliki,

1. the pulling for me doesn't work for me - I get the error (not sure why)
=================================================
[user@dataanalysisserver1 ~]$ git clone git@github.com:3dem/model-angelo.git
Cloning into 'model-angelo'...
Permission denied (publickey).
fatal: Could not read from remote repository.
=================================================

So I just downloaded it from this website.

2. step 3 has yet a typo, I suppose. 
After I run again the 

cd model-angelo
bash install_script.sh

In the main folder "model-angelo-main" where the install_script.sh 
I get the following error - please see below

===================================================
[user@dataanalysisserver1 model_angelo]$ cd ..
[user@dataanalysisserver1 model-angelo-main]$ bash install_script.sh
which: no activate in (/home/user/Data/Software/cryosparc/cryosparc_master/bin:/usr/local/cuda-11.3/bin:/home/user/Data/Software/phenix-1.20.1-4487/build/bin:/home/user/Data/Software/ccp4-8.0/etc:/home/user/Data/Software/ccp4-8.0/bin:/home/user/Data/Software/cryosparc/cryosparc_master/bin:/usr/local/cuda-11.3/bin:/home/user/Data/Software/miniconda/condabin:/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/home/user/Data/Software/Relion/bin:/usr/lib64/openmpi/bin:/home/user/.local/bin:/home/user/bin:/home/user/Data/Software/Relion/bin:/usr/lib64/openmpi/bin)
install_script.sh: line 31: source: model_angelo: is a directory
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Retrieving notices: ...working... done
install_script.sh: line 37: pip: command not found
  File "setup.py", line 12
    sys.path.insert(0, f"{os.path.dirname(__file__)}/model_angelo")
                                                                 ^
SyntaxError: invalid syntax
Did not download weights because the flag -w or --download-weights was not specified
[user@dataanalysisserver1 model-angelo-main]$ conda activate model_angelo
(model_angelo) model_angelo build -h
bash: model_angelo: command not found...
(model_angelo) 
=============================================================

Any idea?

Thank you!

Sincerely,
Dmitry

**Comment by jamaliki** [comment]
Hi, wow this is very strange. Can you delete the model-angelo that you have (the folder with the code). Change 
```
git clone git@github.com:3dem/model-angelo.git
``` 
with 
```
git clone https://github.com/3dem/model-angelo.git
```
Now, you should have a `model-angelo` directory. Can you try the steps again. Sorry for the issues, some of the installation steps need a few users to polish things out.

Thank you so much for being an *early adopter* :)

**Comment by DmitrySemchonok** [comment]
> Hi, wow this is very strange. Can you delete the model-angelo that you have (the folder with the code). Change
> 
> ```
> git clone git@github.com:3dem/model-angelo.git
> ```
> 
> with
> 
> ```
> git clone https://github.com/3dem/model-angelo.git
> ```
> 
> Now, you should have a `model-angelo` directory. Can you try the steps again. Sorry for the issues, some of the installation steps need a few users to polish things out.
> 
> Thank you so much for being an _early adopter_ :)

Hi, 
Sure no problem.

The git worked. But now we have a new error.
Please see below



![3](https://user-images.githubusercontent.com/21281315/193931897-179eae78-91ee-407c-af9f-b529f6ae0fa8.png)

**Comment by jamaliki** [comment]
Sorry for all the back and forth. This is a tiny issue with conda, but I think I know what is going wrong. 
What happens when you run
```
export PATH="/home/user/Data/Software/miniconda/bin:$PATH"
bash install_script.sh
```

**Comment by DmitrySemchonok** [comment]
> Sorry for all the back and forth. This is a tiny issue with conda, but I think I know what is going wrong. What happens when you run
> 
> ```
> export PATH="/home/user/Data/Software/miniconda/bin:$PATH"
> bash install_script.sh
> ```

All good - we are progressing :)
![4](https://user-images.githubusercontent.com/21281315/193937069-8c40ec43-fd55-48c9-a9fc-59e880f8eef5.png)

**Comment by DmitrySemchonok** [comment]
> > Sorry for all the back and forth. This is a tiny issue with conda, but I think I know what is going wrong. What happens when you run
> > ```
> > export PATH="/home/user/Data/Software/miniconda/bin:$PATH"
> > bash install_script.sh
> > ```
> 
> All good - we are progressing :) ![4](https://user-images.githubusercontent.com/21281315/193937069-8c40ec43-fd55-48c9-a9fc-59e880f8eef5.png)

@jamaliki  Sorry I guess I have to be in file mode_angelo. So now it is compiling. I will update you about the results

**Comment by DmitrySemchonok** [comment]
@jamaliki 

Hi,
It seems to work! 

Thank you!

Sincerely,
Dmitry

**Comment by jamaliki** [comment]
Great, thanks for the patience @DmitrySemchonok ! Let me know if you have any other problems :)
