### ISSUE TITLE
Assertion Error: standardize_mrc did not get any inputs

### ISSUE THREAD

**Issue by Srichnew** [3dem/model-angelo#37]
Hi there,

I've been working on installing model angelo and noted a few things.
For context, I'm working on installing it on a cluster using mamba. I found that while doing this, some of the code in the residue_constants.py file within python3.9/site-packages/model_angelo-0.2.3-py3.9.egg/model_angelo/utils was trying to use deprecated Numpy code, I have since altered the code based on the information provided by Numpy (see attached). 
[residue_constants.txt](https://github.com/3dem/model-angelo/files/11162842/residue_constants.txt)

This was the first issue, and was reasonably easy to fix. Following this fix, I was able to start the program using "model_angelo -h", though when I actually try to run the build_no_seq command with a specified --volume-path, **I receive the following error:**

2023-04-05 at 12:31:23 | INFO | ModelAngelo with args: {'volume_path': '/stor1/data/model_angelo_data/test/cryosparc_p163_J37_005_volume_map_sharp.mrc', 'output_dir': '/stor1/data/model_angelo_data/test/test-output', 'mask_path': None, 'device': 'cuda:>
2023-04-05 at 12:31:23 | INFO | Input volume preprocessing with args: {'target_voxel_size': 1.5, 'crop_z': 0, 'bfactor_to_apply': 0, 'auto_mask': False, 'input_path': '/stor1/data/model_angelo_data/test/cryosparc_p163_J37_005_volume_map_sharp.mrc', 'ou>
2023-04-05 at 12:31:23 | ERROR | Error in ModelAngelo
Traceback (most recent call last):

  File "/apps/mamba/envs/model_angelo/bin/model_angelo", line 33, in <module>
    sys.exit(load_entry_point('model-angelo==0.2.3', 'console_scripts', 'model_angelo')())
    │   │    └ <function importlib_load_entry_point at 0x7fc12cf080d0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/apps/mamba/envs/model_angelo/lib/python3.9/site-packages/model_angelo-0.2.3-py3.9.egg/model_angelo/__main__.py", line 51, in main
    args.func(args)
    │    │    └ Namespace(volume_path='/stor1/data/model_angelo_data/test/cryosparc_p163_J37_005_volume_map_sharp.mrc', output_dir='/stor1/da...
    │    └ <function main at 0x7fbe5e1b7160>
    └ Namespace(volume_path='/stor1/data/model_angelo_data/test/cryosparc_p163_J37_005_volume_map_sharp.mrc', output_dir='/stor1/da...
> File "/apps/mamba/envs/model_angelo/lib/python3.9/site-packages/model_angelo-0.2.3-py3.9.egg/model_angelo/apps/build_no_seq.py", line 164, in main
    assert (

**AssertionError: standardize_mrc did not get any inputs: /stor1/data/model_angelo_data/test/cryosparc_p163_J37_005_volume_map_sharp.mrc** 

I'm not really sure what I need to do here. I'm guessing its an issue of file format or something to do with my syntax in terms of defining the .mrc file's path, but regardless I am very confused. Any assistance would be greatly appreciated.

Thanks,
Shane

**Comment by jamaliki** [comment]
Hi!
If I had to guess, it would be that the machine you are running the program on doesn't have the "/stor1" directory mounted. Are you able to check that you can access this file outside of ModelAngelo?

**Comment by Srichnew** [comment]
Hi!
I actually resolved the issue by running the command in the folder containing the file. I then had to alter the numpy code language in the "grid.py" file within the utils folder (just as an update).

**Comment by jamaliki** [comment]
Hmm, which part did you change? BTW, with the release of ModelAngelo-1.0 in a couple of weeks, a lot of this is going to be much simpler :)

**Comment by Srichnew** [comment]
Basically the same deprecated numpy code was the problem. Need to change all "np.int" to "int" and change all "np.float/np.float32" to "float". I went through and checked the code to see if any other deprecated numpy types were present (https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations). Thankfully though, it was just the np.int and np.float/np.float32 that needed changing. I think there were only a total of 5-8 of each.

**Comment by jamaliki** [comment]
Awesome! Yes I had already realized this for ModelAngelo-1.0, which will be out soon. So, you don't mind if I close this issue now?

**Comment by Srichnew** [comment]
Sounds good! great software btw! Very cool and it really does a great job.
