### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by rshek351** [3dem/model-angelo#40]
Hi, I encountered an error when running during the GNN model refinement. /home/roger/.conda/envs/model_angelo/lib/python3.9/site-packages/model_angelo-0.2.2-py3.9.egg/model_angelo/utils/aa_probs_to_hmm.py:88: RuntimeWarning: divide by zero encountered in log
  negative_log_prob = - np.log(aa_probs). I'm not sure what the issue is. The map was generated using the latest cryosparc version and is ~3.0A. Not an issue with the installation since it works fine for another map file. This was wwith sequence provided. Both maps had same sequence and had been processed with cryosparc.

**Comment by rshek351** [comment]
Hi Jamali, the model did not fit the map and was discontinuous. Not error with wrong hand because I was able to dock in a model using phenix. Thanks Jamali!

**Comment by jamaliki** [comment]
What was the resolution for the map? You would expect the lower resolution areas to be more "chopped up"
