### ISSUE TITLE
Model_Angelo build

### ISSUE THREAD

**Issue by TingyuHan0367** [3dem/model-angelo#56]
Hi,

When I was running model_angelo build with -v -pf -c, -c was path with **config.json**.
 In the  config.json "aggressive_pruning": false, but the model_angelo.log with 'aggressive_pruning': True}
I want to know how can I make 'aggressive_pruning' :false in model_angelo build.
Please see the attached images.
![Quicker_20230619_165237](https://github.com/3dem/model-angelo/assets/135953851/b71d6159-02c5-4d61-93f6-c3b0afe72f5f)
![Quicker_20230619_165347](https://github.com/3dem/model-angelo/assets/135953851/a2435473-8bcd-4109-b2f7-cac3e1d2a988)

Thanks,
Tingyu

**Comment by jamaliki** [comment]
Hi Tingyu,

You mean it does not use your provider config file? That is weird, do you mind attaching the full model_angelo.log file?

Best,
Kiarash.

**Comment by TingyuHan0367** [comment]
Hi Kiarash,

Yes, it does not use my provider config file.
 
I attached config file and full model_angelo log file.

![config_file](https://github.com/3dem/model-angelo/assets/135953851/780969b7-d710-417b-8141-db0d57b95a75)
![full_log_file](https://github.com/3dem/model-angelo/assets/135953851/2aa5505f-1925-4004-ba97-dd6bcd633991)


Thanks,
Tingyu

**Comment by jamaliki** [comment]
Hi Tingyu,

You are right. I have been overwriting this variable specifically. Let me push a change, I will let you know once it is patched.

Best,
Kiarash.

**Comment by TingyuHan0367** [comment]
Hi Kiarash,

Thank you for your reply.

 It's very nice to have your help, waiting for your good news.

Best,
Tingyu.

**Comment by jamaliki** [comment]
Hi @TingyuHan0367 ,

Sorry for the long wait, I forgot about this issue. As of ModelAngelo 1.11, this has now been resolved.

Best,
Kiarash.

**Comment by TingyuHan0367** [comment]
Hi Kiarash,

Thank you very much for your reply, which has been very helpful. 

When we updated Relion-5.0, I noticed that you had added the ModelAngelo job, which I am currently trying to use. Thank you very much, this will be a great job.

Best Regards,
Tingyu
