### ISSUE TITLE
ModelAngelo v1.0.1 stopped after predicting Cα

### ISSUE THREAD

**Issue by yanjuisheng** [3dem/model-angelo#58]
Hi jamaliki,

I would like to express my gratitude for your contributions to model building. However, I encountered an issue while using ModelAngelo to generate a protein model. After the Cα prediction step, ModelAngelo displayed an error message in the log file and halted the GNN execution. I have included the error message below. I am confident that the format of the fasta file containing three peptide sequences is correct, and there are no unknown residues in the file. I'm currently unable to determine the cause of the program's termination. Could you kindly provide any guidance on resolving this problem?

Thank you in advance.

2023-06-30 at 17:31:00 | ERROR | Error in ModelAngelo
Traceback (most recent call last):

  File "/opt/anaconda3/envs/model_angelo/bin/model_angelo", line 33, in <module>
    sys.exit(load_entry_point('model-angelo==1.0.1', 'console_scripts', 'model_angelo')())
    │   │    └ <function importlib_load_entry_point at 0x7fd1ce563d90>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/opt/anaconda3/envs/model_angelo/lib/python3.10/site-packages/model_angelo-1.0.1-py3.10.egg/model_angelo/__main__.py", line 52, in main
    args.func(args)
    │    │    └ Namespace(volume_path='/Users/XMi/Desktop/52/1/corner1.mrc', protein_fasta='/Users/XMi/Desktop/52/1/seq.fasta', rna_fasta=Non...
    │    └ <function main at 0x7fd1dafe8700>
    └ Namespace(volume_path='/Users/XMi/Desktop/52/1/corner1.mrc', protein_fasta='/Users/XMi/Desktop/52/1/seq.fasta', rna_fasta=Non...
> File "/opt/anaconda3/envs/model_angelo/lib/python3.10/site-packages/model_angelo-1.0.1-py3.10.egg/model_angelo/apps/build.py", line 241, in main
    gnn_output = gnn_infer(gnn_infer_args)
                 │         └ {'num_rounds': 3, 'crop_length': 200, 'repeat_per_residue': 1, 'esm_model': 'esm1b_t33_650M_UR50S', 'aggressive_pruning': Tru...
                 └ <function infer at 0x7fd1daf1b400>
  File "/opt/anaconda3/envs/model_angelo/lib/python3.10/site-packages/model_angelo-1.0.1-py3.10.egg/model_angelo/gnn/inference.py", line 92, in infer
    protein = get_lm_embeddings_for_protein(lang_model, batch_converter, protein)
              │                             │           │                └ Protein(atom_positions=None, atomc_positions=None, aatype=None, atom_mask=None, atomc_mask=None, residue_index=None, chain_in...
              │                             │           └ <esm.data.BatchConverter object at 0x7fcf8e0e7fd0>
              │                             └ ProteinBertModel(
              │                                 (embed_tokens): Embedding(33, 1280, padding_idx=1)
              │                                 (layers): ModuleList(
              │                                   (0-32): 33 x TransformerLa...
              └ <function get_lm_embeddings_for_protein at 0x7fd1daf1b520>
  File "/opt/anaconda3/envs/model_angelo/lib/python3.10/site-packages/model_angelo-1.0.1-py3.10.egg/model_angelo/data/generate_complete_prot_files.py", line 34, in get_lm_embeddings_for_protein
    protein_with_lm = add_lm_embeddings_to_protein(protein, lm_embeddings)
                      │                            │        └ array([[ 0.0707111 ,  0.16950509, -0.00793343, ..., -0.3184964 ,
                      │                            │                  -0.15484953, -0.44611225],
                      │                            │                 [ 0.24136926, -0.0...
                      │                            └ Protein(atom_positions=None, atomc_positions=None, aatype=None, atom_mask=None, atomc_mask=None, residue_index=None, chain_in...
                      └ <function add_lm_embeddings_to_protein at 0x7fd1daf19cf0>
  File "/opt/anaconda3/envs/model_angelo/lib/python3.10/site-packages/model_angelo-1.0.1-py3.10.egg/model_angelo/utils/protein.py", line 897, in add_lm_embeddings_to_protein
    assert len(lm_embeddings) == input_protein.unified_seq_len
               │                 │             └ 233
               │                 └ Protein(atom_positions=None, atomc_positions=None, aatype=None, atom_mask=None, atomc_mask=None, residue_index=None, chain_in...
               └ array([[ 0.0707111 ,  0.16950509, -0.00793343, ..., -0.3184964 ,
                         -0.15484953, -0.44611225],
                        [ 0.24136926, -0.0...

AssertionError: assert len(lm_embeddings) == input_protein.unified_seq_len

**Comment by jamaliki** [comment]
Hi,

Sorry for my late reply. This seems to be an issue in the input sequence. Have you made sure there are no non standard amino acids in your input? Could you share the sequence file?

Best,
Kiarash.

**Comment by yanjuisheng** [comment]
Hi jamaliki,

Thank you for your help. I recreated a FASTA file and finally ModelAngelo proceeded.
