### ISSUE TITLE
When I try to download weights, my program crashes

### ISSUE THREAD

**Issue by aditya655** [3dem/model-angelo#59]
When I try to download weights using the flag -w or --download-weights, my prompt crashes. What do I do? Btw, I'm doing this using wsl

**Comment by jamaliki** [comment]
Hi,

Do you mind sharing the log of the program when it crashes? I would like to see the error code.

Best,
Kiarash.

**Comment by aditya655** [comment]
Oh hello Kiarash,

Just letting you know that I figured out the problem so you should
just close that issue.

It was an exit code 1, I had a problem with the directory and I just
recloned it again and it worked.

I will let you know if other issues arise.

From,
Aditya Duggirala

**Comment by aditya655** [comment]
Also my memory issue was fixed as well.

I just had a remote connection to a machine instead.

**Comment by jamaliki** [comment]
Ohhh, great! Thanks!
