### ISSUE TITLE
FASTA filename extension

### ISSUE THREAD

**Issue by kttn8769** [3dem/model-angelo#6]
My calculation failed in the below lines of model_angelo.gnn.inference.infer(), because I used a FASTA file with '.fa' extension.

https://github.com/3dem/model-angelo/blob/8b57c9ddd675480ca24d017997225de023d38bed/model_angelo/gnn/inference.py#L263-L264

According to Wikipedia, a FASTA format filename extension for a amino-acid sequence can be {.fasta, .fa, .faa, .mpfa}, so I think at least these extensions should be accepted. Or an appropriate FASTA format checker should be implemented?

(It will be also helpful if the file format/extension check is performed at the very beginning of the entire program.)

Thank you.

**Comment by jamaliki** [comment]
Yes I will change this to allow all four formats, as well as check the format before running. That makes sense.

**Comment by jamaliki** [comment]
Fixed!

**Comment by kttn8769** [comment]
Thank you for the quick fix.
By the way model_angelo just showed me a strikingly good performance for my unpublished protein (homo-multimer). Thank you for your great work.

**Comment by jamaliki** [comment]
Oh that is great to hear! If you would like to share just a snippet of the model, you can send it to me to my [email](mailto:kjamali@mrc-lmb.cam.ac.uk)
