### ISSUE TITLE
Model editing on coot

### ISSUE THREAD

**Issue by say-00** [3dem/model-angelo#65]
Hi,

This program works for me well! When I try to edit the generated coordinate model in coot, the coot interface disappears and I cannot continue modeling. Is there any solution to avoid this problem?

For example, 
1. download emd_15206 electron density map as emd_15206.mrc
2. $ model_angelo build -v emd_15026.mrc -pf avidin.fasta -o avidin
3. open avidin.cif on coot
4. delete one of the residue
5. coot is gone

**Comment by jamaliki** [comment]
Hi,

Thank you for using ModelAngelo! This is strange and may be due to some subtle issue with our mmCIF file. However, it is hard to debug this from our end. Is it possible for you to contact the COOT developers?

Best,
Kiarash.

**Comment by say-00** [comment]
Hi Kiarash,

Thank you for a message. I will post on ccpem.

Best,
Seiichi
