### ISSUE TITLE
Model Angelo crashes after first round 

### ISSUE THREAD

**Issue by cyntiaT** [3dem/model-angelo#68]
Hi there!

First and foremost, thank you so much for providing this incredible software!

I recently tried to use the latest version available, but I encountered an issue where the job abruptly stops at the end of round 1. It seems that the error is related to the 3D  structure, specifically, I'm receiving a "KeyError: '_atom_site.id'" message. Would it be possible for you to assist me with this issue?

Your help would be greatly appreciated. Thank you in advance!

[model_angelo.log](https://github.com/3dem/model-angelo/files/12565746/model_angelo.log)

**Comment by jamaliki** [comment]
Hi,

Thank you for using ModelAngelo! Sorry for the cryptic error message, but it seems to have not found any C-alpha atoms in your map. Could it be a) the map is in the wrong handedness and you need to flip it? or b) that the map has resolution lower than 4A?

Best,
Kiarash.

**Comment by cyntiaT** [comment]
Hi!

I picked another map with a better resolution, which solved the problem. 

Thank you very much for your help!
Best, 

Cyntia

**Comment by jamaliki** [comment]
Excellent! If you don't mind I will close the issue.
