### ISSUE TITLE
Model angelo not using GPUs

### ISSUE THREAD

**Issue by tailinhua16** [3dem/model-angelo#7]
Dear developers,
hi, I'm trying to use model angelo to build model on a 8x Rtx5000 machine with CentOS 7, cuda 10.1, and when I ran the 'model_angelo build -v Refs/Sharp.mrc -f astas/sequence.fa -o OutPut' command, I got the folloing output as:

/home/linhua/Programs/anaconda3/envs/model_angelo/lib/python3.9/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484809662/work/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0

It seems model angelo's not using GPUs while I do have them?

During compiling the package, I got the folloing message at the end:
.
Installed /home/linhua/Programs/anaconda3/envs/model_angelo/lib/python3.9/site-packages/model_angelo-0.0.1-py3.9.egg
Processing dependencies for model-angelo==0.0.1
Finished processing dependencies for model-angelo==0.0.1
Did not download weights because the flag -w or --download-weights was not specified
[linhua@localhost model-angelo]$ 

Does not able to download the weights have something to do with not able to use GPUs?

Thank you very much in advance!
Sincerely,
Linhua Tai

**Comment by jamaliki** [comment]
Hi, thank you for using ModelAngelo. You have CUDA 10.1 installed, so you need to modify the installation script in the line
```
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
```
it should be
```
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
```
Could you try removing the model_angelo conda environment with `conda env remove -n model_angelo` and then try running your modified installation script again?

**Comment by tailinhua16** [comment]
Dear Kiarash,
Hi,
thanks to your tip, it worked perfectly, but now I've encountered an another issue, seems the program somehow decided to stop running itself, the output are as follows:

model_angelo build -v Refs/FFAR_Acid_Sharp.mrc -f Fastas/FFAR2-sequence.fa -o FFAR2-Acid_OutPut
---------------------------- ModelAngelo -----------------------------
By Kiarash Jamali, Scheres Group, MRC Laboratory of Molecular Biology
--------------------- Initial C-alpha prediction ---------------------
100%|█████████████████████████████████████████| 512/512 [11:55<00:00,  1.40s/it]
------------------ GNN model refinement, round 1 / 3 ------------------
(model_angelo)

It kind of stopped at round 1, any idea what might cause this problem?

Thank you again!
Sincerely,
Linhua Tai

**Comment by tailinhua16** [comment]
Dear Kiarash,
Hi,
thanks to your tip, it worked perfectly, but now I've encountered an another issue, seems the program somehow decided to stop running itself, the output are as follows:

model_angelo build -v Refs/Sharp.mrc -f Fastas/sequence.fa -o OutPut
---------------------------- ModelAngelo -----------------------------
By Kiarash Jamali, Scheres Group, MRC Laboratory of Molecular Biology
--------------------- Initial C-alpha prediction ---------------------
100%|█████████████████████████████████████████| 512/512 [11:55<00:00,  1.40s/it]
------------------ GNN model refinement, round 1 / 3 ------------------
(model_angelo)

It kind of stopped at round 1, any idea what might cause this problem?

Thank you again!
Sincerely,
Linhua Tai

**Comment by jamaliki** [comment]
Hi,
Yes, seems like it crashed in the GNN round. Can you send me the file `OutPut/model_angelo.log` please
