### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by ChenShengsGitHub** [3dem/model-angelo#86]
In section 3.2 of the article, the dimension M of X and the dimension M of S are the same. But in my understanding, the dimension M of X cannot match the dimension M of S during inference. Is it because I didn't understand it clearly?

**Comment by jamaliki** [comment]
Hi, 

Thank you for the question. I believe that is a typo, since it is supposed to be $M'$ for the length of the sequence embedding that is not generally equal to $M$ that is the number of residues.

**Comment by ChenShengsGitHub** [comment]
Thanks for your reply! I have another question, X is the coordinate of the unordered residue, and S is the ordered residue sequence, which is inconsistent with AlphaFold. I would like to know if you try to align X and S in the neural network, such as through attention.

**Comment by jamaliki** [comment]
Yes, in our case, we do not have access to the ordering between $X$ and $S$, which makes our problem different. The network learns this correspondence through the use of its Sequence Module. 

In fact in model building, there may be residues in $S$ that are not resolvable in the map, so they would be missing in $X$, so a learned approach is necessary.

Feel free to ask any other questions!
