### ISSUE TITLE
Small bug with hmm files names.

### ISSUE THREAD

**Issue by reorocha** [3dem/model-angelo#91]
Hello,

I am currently running the Angelo model locally in No-Seq mode for an extensive map where I anticipate a significant number of chains. This implies that chain IDs with identical letters but different combinations of lowercase and uppercase (e.g., EU and Eu) may appear in the final model. However, despite the potential existence of multiple chains, only one HMM file for each letter combination is generated at the end of the process. For instance, in the output, only "EU.hmm" is observed.

What adds to the complexity is that, oddly, the header of this file contains:

yaml
Copy code
HMMER3/f [3.2 | April 2018]
                NAME  Eu
                LENG  39
                ALPH  amino
                RF    no
                MM    no
                CONS  yes
                CS    no
                MAP   yes
As evident from the second line, the name inside the file corresponds to the alternate combination, featuring a lowercase "u." However, both chains (EU and Eu) are present in the output .cif model. My hypothesis is that the correct "EU.hmm" file is somehow being replaced by the "Eu.hmm" file, which has an incorrect name.

I hope this information proves helpful in resolving the issue.

**Comment by jamaliki** [comment]
Hi @reorocha ,

This is fascinating. May I ask if this is in Windows? Because I cannot see any reason why this would be an issue from the code itself. However, Windows has this lovely property of treating upper and lower-case file names as the same.

If this is an issue, I may have a fix, but please let me know.

Best,
Kiarash.

**Comment by reorocha** [comment]
Hi @jamaliki,

It appears that this is indeed the case. It seems that copying the files from Ubuntu to a Windows PC using SSH has somehow altered the files. If you have a solution for this issue, I would greatly appreciate your assistance!

Thanks for your help.

**Comment by jamaliki** [comment]
Hi,

As of ModelAngelo 1.0.11, this is now solved. However, you would have to rebuild your map with the new version. Another option is to rename the files with a Python script (I can provide you one), as long as you have access to the original files on a *nix machine.

**Comment by reorocha** [comment]
Thank you! It worked as a charm :)
